# -*- coding: utf-8 -*-
"""Correlation Concept.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/13pYAoq1jCZa-a_AtrGya7mVe-uNB-ek5
"""

import pandas as pd
import numpy as np

# Seed for reproducibility
np.random.seed(42)

# Genereate sample data
data = {
    'Age' : np.random.normal(30,10,100).astype(int),
    'Annual Income (K$)' : np.random.normal(50,20,100).astype(int),
    'Spending Score (1-100)' : np.random.randint(1,100,100),
    'Years with Company' : np.random.normal(5,2,100).astype(int)
}

# Create DataFrame
df = pd.DataFrame(data)
df

pip install tabulate

from tabulate import tabulate

correlation_matrix = df.corr()

# Print the correlation matrix as table
print(tabulate(correlation_matrix, headers = 'keys', tablefmt='grid', numalign="right", floatfmt=".2f"))